/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S3;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author juse
 */
public class TiempoSatelital extends javax.swing.JFrame {

    private Simulador simulador;

    /**
     * Creates new form TiempoSatelital
     */
    public TiempoSatelital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        madrid = new javax.swing.JButton();
        andalucia = new javax.swing.JButton();
        barcelona = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        madrid.setText("Madrid");
        madrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madridActionPerformed(evt);
            }
        });
        getContentPane().add(madrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, -1));

        andalucia.setText("Andalucia");
        andalucia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andaluciaActionPerformed(evt);
            }
        });
        getContentPane().add(andalucia, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        barcelona.setText("Barcelona");
        barcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcelonaActionPerformed(evt);
            }
        });
        getContentPane().add(barcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/S3/mapa.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void madridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madridActionPerformed
        VentanaTemperatura madrid = new VentanaTemperatura();
        simulador.addObserver(madrid);
        madrid.setVisible(true);
    }//GEN-LAST:event_madridActionPerformed

    private void andaluciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andaluciaActionPerformed
        VentanaTemperatura andalucia = new VentanaTemperatura();
        simulador.addObserver(andalucia);
        andalucia.setVisible(true);
    }//GEN-LAST:event_andaluciaActionPerformed

    private void barcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcelonaActionPerformed
        VentanaTemperatura barcelona = new VentanaTemperatura();
        simulador.addObserver(barcelona);
        barcelona.setVisible(true);
    }//GEN-LAST:event_barcelonaActionPerformed

    void setSimulador(Simulador sim) {
        simulador = sim;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton andalucia;
    private javax.swing.JButton barcelona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton madrid;
    // End of variables declaration//GEN-END:variables
}
