/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S4;

import static java.awt.Color.*;


/**
 *
 * @author juse
 */
public class PanelBotones extends javax.swing.JPanel {

    private EstadoMotor estado;
    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
        estado = EstadoMotor.APAGADO;
        //estado necesario para comunicarselo al cliente
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EtiqMostrarEstado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        BotonAcelerar = new javax.swing.JToggleButton();
        BotonFrenar = new javax.swing.JToggleButton();
        BotonEncender = new javax.swing.JToggleButton();

        EtiqMostrarEstado.setBackground(new java.awt.Color(254, 254, 254));
        EtiqMostrarEstado.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        EtiqMostrarEstado.setForeground(java.awt.Color.red);
        EtiqMostrarEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EtiqMostrarEstado.setText("APAGADO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EtiqMostrarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BotonAcelerar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BotonAcelerar.setText("ACELERAR");
        BotonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarActionPerformed(evt);
            }
        });

        BotonFrenar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BotonFrenar.setText("FRENAR");
        BotonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFrenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(BotonAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(BotonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonFrenar)
                    .addComponent(BotonAcelerar))
                .addContainerGap())
        );

        BotonEncender.setBackground(new java.awt.Color(254, 254, 254));
        BotonEncender.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        BotonEncender.setForeground(java.awt.Color.green);
        BotonEncender.setText("ENCENDER");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonEncender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(BotonEncender)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        if(BotonEncender.isSelected())
        {
            BotonEncender.setText("APAGAR");
            BotonEncender.setForeground(RED);
            EtiqMostrarEstado.setText("ENCENDIDO");
            
            estado = EstadoMotor.ENCENDIDO;
        }  
        else{

            //reiniciar todos los botones
            BotonEncender.setText("ENCENDER");
            BotonEncender.setForeground(BLACK);
            
            BotonFrenar.setText("FRENAR");
            BotonFrenar.setForeground(BLACK);
            
            BotonAcelerar.setText("ACELERAR");
            BotonAcelerar.setForeground(BLACK);
            
            BotonAcelerar.setSelected(false);
            BotonFrenar.setSelected(false);
            
            EtiqMostrarEstado.setText("APAGADO");
            estado = EstadoMotor.APAGADO;
        }
    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFrenarActionPerformed
        
        if(BotonEncender.isSelected() && !BotonAcelerar.isSelected())
        {
            BotonFrenar.setText("FRENANDO");
            BotonFrenar.setForeground(RED);
            
            estado = EstadoMotor.FRENANDO;
        }
        else{
            BotonFrenar.setSelected(false);
            estado = EstadoMotor.ENCENDIDO;
        }
        if(!BotonFrenar.isSelected())
        {
            BotonFrenar.setText("FRENAR");
            BotonFrenar.setForeground(BLACK);
            BotonFrenar.setSelected(false);
        }
        
        
        /*if(BotonEncender.isSelected() && !BotonAcelerar.isSelected())
        {
            BotonFrenar.setText("FRENANDO");
            BotonFrenar.setForeground(RED);
            
            estado = EstadoMotor.FRENANDO;
        }
        else
        {
            BotonFrenar.setText("FRENAR");
            BotonFrenar.setForeground(BLACK);
            
            estado = EstadoMotor.ENCENDIDO;
        }*/
        
    }//GEN-LAST:event_BotonFrenarActionPerformed

    private void BotonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarActionPerformed
        if(BotonEncender.isSelected() && !BotonFrenar.isSelected())
        {
            BotonAcelerar.setText("ACELERANDO");
            BotonAcelerar.setForeground(RED);
            
            estado = EstadoMotor.ACELERANDO;
        }
        else{
            BotonAcelerar.setSelected(false);
            estado = EstadoMotor.ENCENDIDO;
        }
        if(!BotonAcelerar.isSelected())
        {
            BotonAcelerar.setText("ACELERAR");
            BotonAcelerar.setForeground(BLACK);
            BotonAcelerar.setSelected(false);
        }
        
    }//GEN-LAST:event_BotonAcelerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAcelerar;
    private javax.swing.JToggleButton BotonEncender;
    private javax.swing.JToggleButton BotonFrenar;
    private javax.swing.JLabel EtiqMostrarEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
