/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package S4;

import java.awt.BorderLayout;
import java.awt.event.WindowAdapter;
import java.util.concurrent.TimeUnit;

/**
 *
 * @author juse
 */
public class Salpicadero extends javax.swing.JPanel {

    private double rpm;
    private double velocidad;
    private double distancia;
    private long inicio;
    private long fin;
    
    static final double RADIO = 0.15;

    /**
     * Creates new form Salpicadero
     */
    public Salpicadero() {
        initComponents();
        inicio = System.currentTimeMillis();
        fin = 0;
        this.setLayout(new BorderLayout());
        
        Velocimetro velocimetro = new Velocimetro();
        velocimetro.setVisible(true);
        this.add(velocimetro);
        
        CuentaKilometros cuentaKilometros = new CuentaKilometros();
        cuentaKilometros.setVisible(true);
        this.add(cuentaKilometros,BorderLayout.PAGE_END);
        
        CuentaRevoluciones cuentaRevoluciones = new CuentaRevoluciones();
        cuentaRevoluciones.setVisible(true);
        this.add(cuentaRevoluciones,BorderLayout.EAST);
        
        //podriamos hacer una variable que sea duracion o algo asi
    }
    
    double getVelocidad()
    {
        return velocidad;
    }
    
    void velocidad()
    {
        velocidad = 2*Math.PI*RADIO * rpm * (60.0/1000);
        System.out.println(velocidad);
        //hay que hacerlo asi, de la otra forma velocidad nos daba siempre cero
    }
    
    double duracion(){
        long tiempo = fin - inicio;       
        double duracion = (double)TimeUnit.MILLISECONDS.toSeconds(tiempo)/3600;
        return duracion;
    }
    
    double ejecutar(double revoluciones, EstadoMotor estadoMotor)
    {
        fin = System.currentTimeMillis();
        this.rpm = revoluciones;
        this.velocidad();
        this.distancia = this.velocidad * this.duracion();
   
        return rpm;
    }

    void addWindowListener(WindowAdapter windowAdapter) {
        //creo que no hay que hacer nada
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
